name: Deploy Laravel Application

on:
  push:
    branches:
      - bahadur

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, gd, bcmath, zip, grpc
        ini-values: post_max_size=256M, upload_max_filesize=256M
        coverage: none
 
    - name: composer
      run: composer update


    - name: Deploy to Bahadur
      if: github.ref == 'refs/heads/bahadur'
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: panel.saivra.co
        username: ${{ secrets.FTP_USERNAME  }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # Your project directory
        server-dir: ./httpdocs/ # Subdomain directory on the server

    - name: Clear Laravel Cache on bahadur
      if: github.ref == 'refs/heads/bahadur'
      run: ssh root@82.180.131.168 "php  panel.saivra.co/httpdocs/artisan config:cache"
